src/components/FilterUser/index.tsx, src/pages/users/index.tsx
This component is a form with text field and when submitted calls handleSubmit function to filter users.
=> Create component for filter by user name

.eslintrc.json, src/modules/authentication/pages/LoginPage/LoginPage.test.tsx, src/modules/authentication/pages/LoginPage/LoginPage.tsx, src/modules/communities/mocks/MockedCommunity.ts, src/modules/communities/pages/CommunityPage/CommunitiesDisplay/CommunitiesDisplayPage.styles.ts, src/modules/communities/pages/CommunityPage/CommunitiesDisplay/CommunitiesDisplayPage.test.tsx, src/modules/communities/pages/CommunityPage/CommunitiesDisplay/CommunitiesDisplayPage.tsx, src/modules/communities/pages/CommunityPage/CommunityManagementPage/CommunityManagementPage.test.tsx, src/modules/communities/pages/CommunityPage/CommunityManagementPage/CommunityManagementPage.tsx, src/modules/communities/pages/CommunityPage/components/CommunityCard/CommunityCard.tsx, src/routes/routesCoordinator.ts, tsconfig.json
##O QUE FOI REALIZADO
feat 1 - Marivone/Wallace - Created Community Management Page. Created function on the CommunitiesDisplayPage. Created new route.
feat 2 - Marivone -  Filter styling and its function working on CommunityDisplayPage
feat 3 - Marivone -  Added validation for empty results on search bar
##IMAGENS 1
##IMAGENS 2
##IMAGENS 3
=> feat(communities): 'Created CommunityManagementePage,function on CommunitiesDisplayPage and route'

src/modules/communities/pages/CreateAndEditCommunity/CreateAndEditCommunity.test.tsx
Remoção de um código que foi utilizado durante os testes unitários.
=> refactor: Removing debugging code

.husky/pre-commit, package.json
Adicionamos:
- Configuração de valores mínimos de cobertura de código 
- Script para teste de cobertura e execução antes dos commits
- Bloqueamos caso um commit reduza a cobertura atual
_Print do terminal com informações sobre a  cobertura atual de código._
Informações do print
- 50.68% statements
- 35.22% branches 
- 51.9% functions 
- 52.57% lines
=> chore: Configure minimum threshold enforcement for coverage results

README.md
Atualização no README para inclusão de informações sobre como o código é integrado é liberado nos ambientes de DEV e PROD.
=> docs: Updating informations about main and production branchs

.github/workflows/dev_netlify.yml
- Atualizamos arquivo `dev_netlify.yml` (formatação errada)
- Incluimos o `npm ci` para instalação de dependências
Mais informações sobre npm ci (https://docs.npmjs.com/cli/v8/commands/npm-ci)
=> fix: Update dev_netlify

.eslintignore, .eslintrc.json, .husky/pre-commit, package.json, src/modules/communities/pages/CommunityPage/CommunitiesDisplay/CommunitiesDisplayPage.test.tsx, src/modules/communities/pages/CommunityPage/CommunityManagementPage/CommunityManagementPage.test.tsx, src/modules/dashboard/pages/DashboardPage/fragments/MultipleCharts/MultipleCharts.tsx, src/modules/users/pages/UserDetailPage/components/UserDetailInfo/UserDetailInfo.test.tsx, src/modules/users/pages/UserPage/components/UserCard/UserCard.test.tsx, src/setupTests.tsx, src/shared/assets/icons/CommunitiesIcon.tsx
- Adicionamos scripts lint e lint:fix (usando eslint)
- Adicionamos scripts lint:format  (usando prettier)
- Resolvemos os dezesseis problemas encontrados (ver print)
_Obs.: Seguimos usando o padrão pre-configurado só adicionamos os scripts._
scripts
```
npm run lint // detecta arquivos que estão fora do padrão
npm run lint:fix // detecta e edita os arquivos com padrão (quando possível) 
npm run lint:format // detecta e edita os arquivos para o padrão
```
=> chore: Add scripts to run lint and format code

src/modules/authentication/pages/LoginPage/LoginPage.test.tsx, src/modules/authentication/pages/LoginPage/LoginPage.tsx, src/modules/communities/pages/CommunityPage/CommunityManagementPage/CommunityManagementPage.tsx, src/modules/users/pages/RegisterUser/RegisterUserPage.test.tsx, src/modules/users/pages/RegisterUser/RegisterUserPage.tsx, src/modules/users/pages/RegisterUser/components/RegisterUserForm/RegisterUserForm.test.tsx, src/modules/users/pages/RegisterUser/components/RegisterUserForm/RegisterUserForm.tsx, src/modules/users/services/UserService.ts, src/setupTests.tsx, src/shared/components/CustomCardWithIcon/CustomCardWithIcon.test.tsx, src/shared/components/CustomCardWithIcon/CustomCardWithIcon.tsx, src/shared/components/EmptyState/EmptyState.test.tsx, src/shared/components/EmptyState/EmptyState.tsx, src/shared/components/Select/Select.test.tsx, src/shared/components/index.tsx
- Alteramos o redirecionamento depois do login com sucesso para tela de seleção de comunidade
- Adicionamos o link para cadastro de usuária
=> feat: Add link register in community home

src/modules/dashboard/pages/DashboardPage/fragments/MultipleCharts/MultipleCharts.tsx, src/shared/components/PolarAreaChart/PolarAreaChart.tsx, src/shared/components/VerticalBarChart/VerticalBarChart.tsx
=> fix: Fixing CI not running during testing

src/shared/components/Menu/Menu.test.tsx, src/shared/components/Menu/MenuItems.ts
Alteração do botão de comunidades para redirecionar o fluxo para a tela de seleção de comunidades.
=> feat: Community button now links to selection

src/modules/communities/pages/CommunityPage/CommunityManagementPage/CommunityManagementPage.tsx, src/modules/communities/pages/CommunityPage/components/CommunityMenu/CommunityMenu.tsx, src/shared/components/PageTitle/PageTitle.tsx
Adição do botão de edição na tela home das comunidades.
=> feat(communities): Creating a link to community editing on home

src/modules/communities/pages/CommunityPage/CommunityManagementPage/CommunityManagementPage.styles.ts, src/modules/communities/pages/CommunityPage/CommunityManagementPage/CommunityManagementPage.tsx
Editei o alinhamento do título em relação à opção de edição e a margem da tela.
=> style(communities): Edited CommunityManagementPage styling Grid

src/modules/bicycles/mocks/BikeMocks.ts, src/modules/bicycles/services/BikeService.test.ts, src/modules/bicycles/services/BikeService.ts
=> fix: Fixing counter for available bikes

README.md
Edit readme to include test-coverage run information
=> Edit readme to include test-coverage run information

CHANGELOG.md
=> docs: Modifying changelog for 2.0.2

src/modules/communities/pages/CommunityPage/components/CreateCommunityButton/CreateCommunityButton.tsx
O nome do arquivo e o nome do componente no codigo estavam inconsistentes.
=> refactor: Making component names consistent

src/modules/users/pages/RegisterUser/components/RegisterUserForm/components/MotivationForm/MotivationForm.test.tsx, src/modules/users/pages/RegisterUser/components/RegisterUserForm/components/MotivationForm/MotivationForm.tsx
BREAKING CHANGE:
Removed bike motivation aditional option
Removed bike motivation aditional option
=> feat(custom): Removed bike motivation aditional option

src/modules/dashboard/pages/DashboardPage/fragments/Dashboard/Dashboard.tsx
feat(dashboard): Changed label for customCard in dashboard
Antes
Depois
=> feat(dashboard): Changed label for customCard in dashboard

src/modules/dashboard/pages/DashboardPage/components/TravelTimeCard/TravelTimeCard.test.tsx, src/modules/dashboard/pages/DashboardPage/components/TravelTimeCard/TravelTimeCard.tsx
A dashboard exibe atualmente um valor em minutos da quantidade de viagens. Este PR muda esta exibição para horas.
=> feat(dashboard): Switching display minutes to hours on the dashboard

src/modules/dashboard/pages/DashboardPage/fragments/Dashboard/Dashboard.tsx
feat(dashboard): Altered DonutPercentageCard for new bikers
- [] Foi realizado uma revisão por outra pessoa do meu código
Depois
Segunda alteração
=> feat(dashboard): Altered DonutPercentageCard for new bikers

src/modules/dashboard/pages/DashboardPage/fragments/MultipleCharts/MultipleCharts.tsx
feat(dashboard): Created a user label for MultipleCharts
=> feat(dashboard): Created a user label for MultipleCharts

src/modules/dashboard/pages/DashboardPage/components/TravelTimeCard/TravelTimeCard.tsx, src/modules/dashboard/pages/DashboardPage/fragments/Dashboard/Dashboard.tsx
feat(custom): Altered plane icon for bike icon in TravelTimeCard
Antes
Depois
=> feat(custom): Altered plane icon for bike icon in TravelTimeCard

.github/pull_request_template.md
PR Template para versões em PROD
=> docs: PROD PR Template

src/modules/users/models/enums/Reason.enum.ts, src/modules/users/models/enums/index.ts, src/modules/users/models/types/Reason.type.ts, src/modules/users/models/types/index.ts, src/modules/users/pages/RegisterUser/components/RegisterUserForm/RegisterUserForm.schema.ts, src/modules/users/pages/RegisterUser/components/RegisterUserForm/RegisterUserForm.tsx, src/modules/users/pages/RegisterUser/components/RegisterUserForm/components/MotivationForm/MotivationForm.test.tsx, src/modules/users/pages/RegisterUser/components/RegisterUserForm/components/MotivationForm/MotivationForm.tsx
feat(users): Created additional option in MotivationForm
=> feat(users): Created additional option in MotivationForm

src/modules/users/pages/RegisterUser/components/RegisterUserForm/components/SocialInfoForm/SocialInfoForm.tsx
Simbolo para renda estava com a sintaxe de forma incorreta. Seguindo a sugestão da cliente, para a faixa inicial, também se colocou o intervalo.
=> fix(users): Adjusting symbol for income

src/modules/dashboard/pages/DashboardPage/fragments/Dashboard/Dashboard.tsx
A pedido da cliente, inserção e edição de legendas no gráfico relacionado à motivação de uso de bicicletas durante os empréstimos.
=> style(dashboard): Adjusting label in horizontalBarCHart

src/modules/communities/pages/CommunitiesPages/CommunityManagementPage/CommunityManagementPage.tsx
feat(communities): Adicionei o botão de emprestar bicicleta no Gerenciador de Comunidades.
=> feat(communities): Added lendBike card on CommunityManagementPage

src/modules/communities/pages/CommunitiesPages/CommunityManagementPage/CommunityManagementPage.test.tsx, src/modules/communities/pages/CommunitiesPages/CommunityManagementPage/CommunityManagementPage.tsx
Card para devolução de bicicletas inserido na tela de gerenciamento de comunidades.
=> feat(communities): Return bike card on Community Management Page

src/modules/communities/pages/CommunitiesPages/CommunitiesSelectionPage/CommunitiesSelectionPage.test.tsx, src/modules/users/pages/RegisterUser/components/RegisterUserForm/components/MotivationForm/MotivationForm.test.tsx, src/modules/users/pages/RegisterUser/components/RegisterUserForm/components/ProblemsForm/ProblemsForm.test.tsx
A forma com que os testes validavam valores numéricos pode conter pontos de falha. Alterei a forma para uma mais assertiva.
=> refactor: Refactor validations on tests for numerical values

README.md
Uma limpeza no README e um detalhamento maior no processo para deploy.
=> docs: Cleanup on README

CONTRIBUTING.md
Limpeza no texto do contributing
=> docs: Cleanup on CONTRIBUTING

README.md
Adição de procedimentos iniciais para configuração do ambiente local.
=> docs: Adding initial configuration to the readme

src/modules/dashboard/pages/DashboardPage/fragments/Dashboard/Dashboard.tsx, src/shared/components/Menu/MenuItems.ts
- [ x] Realizei uma auto-revisão do meu código
- [ x] Fiz as alterações correspondentes na [documentação](https://docs.google.com/document/d/1u5xQt_3wQT_FJdKiu6U8Qut07MNALmpjv5qIaZzepJc/edit#heading=h.v0v8hzy8gdby)
- [ x] Meu código segue as diretrizes de estilo deste projeto
- [x ] Testes de unidade novos e existentes são aprovados localmente com minhas alterações
- [ x] Inseri na PR captura de tela da feature desenvolvida
=> fix(dashboard): changed menu text and presentation text

src/modules/communities/pages/CommunitiesPages/CommunitiesSelectionPage/CommunitiesSelectionPage.styles.ts, src/modules/communities/pages/CommunitiesPages/CommunitiesSelectionPage/CommunitiesSelectionPage.tsx, src/modules/communities/pages/CommunitiesPages/components/CommunityCard/CommunityCard.styles.ts, src/modules/communities/pages/CommunitiesPages/components/CommunityCard/CommunityCard.tsx
Foi feita a correção no campo de filtragem de comunidades que estava com a responsividade errada quando o site era aberto por um dispositivo móvel.
=> Community filter input field responsive

src/modules/bicycles/pages/LendBike/LendBikeCards/SelectBikeUserPage/SelectBikeUserPage.styles.ts, src/modules/bicycles/pages/LendBike/LendBikeCards/SelectBikeUserPage/SelectBikeUserPage.test.tsx, src/modules/bicycles/pages/LendBike/LendBikeCards/SelectBikeUserPage/SelectBikeUserPage.tsx, src/modules/bicycles/pages/LendBike/LendBikeNextStep.tsx, src/modules/bicycles/pages/LendBike/LendBikePage.styles.ts, src/routes/routesCoordinator.ts
Criado novas rotas e componentes para Emprestar Bicicleta
- [] Testes de unidade novos e existentes são aprovados localmente com minhas alterações
=> Criado novas rotas e componentes para Emprestar Bicicleta

src/modules/users/pages/RegisterUser/RegisterUserPage.styles.ts, src/modules/users/pages/RegisterUser/RegisterUserPage.tsx
style(users): Corrigi a margin top em RegisterUserPage
=> style(users): Correcting margin top for RegisterUserPage

src/modules/users/models/enums/Reason.enum.ts, src/modules/users/models/types/Reason.type.ts, src/modules/users/models/types/index.ts, src/modules/users/pages/RegisterUser/components/RegisterUserForm/RegisterUserForm.schema.ts, src/modules/users/pages/RegisterUser/components/RegisterUserForm/components/MotivationForm/MotivationForm.test.tsx, src/modules/users/pages/RegisterUser/components/RegisterUserForm/components/MotivationForm/MotivationForm.tsx, src/modules/users/services/UserService.ts
Foi feita a criação de um enum para corresponder com os campos de seleção da motivação de uso da bike.
=> Change user motivation field

src/modules/bicycles/components/BikeCard/BikeCard.tsx, src/modules/bicycles/components/BikeUserCard/BikeUserCard.tsx, src/modules/bicycles/components/SelectBikePage/SelectBikePage.test.tsx, src/modules/bicycles/components/SelectBikePage/SelectBikePage.tsx, src/modules/bicycles/mocks/FormValuesMock.ts, src/modules/bicycles/pages/BikeConfirmationPage/BikeConfirmationPage.test.tsx, src/modules/bicycles/pages/BikeConfirmationPage/BikeConfirmationPage.tsx, src/modules/bicycles/pages/BikeFinalPage/BikeFinalPage.test.tsx, src/modules/bicycles/pages/BikeFinalPage/BikeFinalPage.tsx, src/modules/bicycles/pages/LendBike/LendBikeNextStep/LendBikeNextStep.test.tsx, src/modules/bicycles/pages/ReturnBike/ReturnBikePage.test.tsx
Criados os testes faltantes para as páginas novas dos fluxos de emprestar e devolver bicicletas.
=> Bike pages tests

src/modules/dashboard/pages/DashboardPage/components/DonutPercentageCard/DonutPercentageCard.tsx
Fiz uma verificação para impedir a divisão por 0 quando não há viagens na comunidade cadastrada.
Antes:
Depois:
=> fix(dashboard): Fix NAN problem when divided by 0

src/modules/users/pages/RegisterUser/components/RegisterUserForm/RegisterUserForm.schema.ts, src/modules/users/services/UserService.ts
- Solve telephone database value issue;
- Set default value in SchoolingStatus.
=> Database missing data

src/modules/bicycles/services/BikeService.test.ts, src/modules/bicycles/services/BikeService.ts, src/modules/communities/services/CommunityService.test.ts, src/modules/communities/services/CommunityService.ts, src/modules/dashboard/services/DashboardService.ts, src/modules/dashboard/utils/DashboardTranslate.ts, src/modules/users/models/enums/Racial.enum.ts, src/modules/users/models/enums/Schooling.enum.ts, src/modules/users/models/types/Racial.type.ts, src/modules/users/pages/RegisterUser/components/RegisterUserForm/RegisterUserForm.schema.ts, src/modules/users/pages/RegisterUser/components/RegisterUserForm/components/SocialInfoForm/SocialInfoForm.test.tsx, src/modules/users/services/UserService.ts, src/shared/utils/DateUtils.test.ts, src/shared/utils/DateUtils.ts
Foram feitas alterações nas funcionalidades de empréstimo e devolução de bicicletas para que emitam alterações no dashboard, além disso, foram feitas correções em problemas que ocorriam nas estruturas "devolutions" e "withdraws" da entidade "bike" que impediam seu correto uso na versão app do Bota pra Rodar.
=> Dashboard Update + Lend/Return Bike fix

database/database-guide.md, database/sample-db.json
Criei uma pasta com um json para ser importado e utilizado ao criar um novo banco no firebase que possa ser consumido pelo Bota pra Rodar Web. Além disso, há um arquivo "database-guide.md" explicando o passo a passo na criação desse banco que pode ser replicado por qualquer usuário que queira contribuir, eliminando a necessidade de dar acesso ao banco de dev atualmente utilizado pelos membros do projeto na Ameciclo.
=> Firebase Database creation guide
